# Generated by Django 5.0.7 on 2024-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграм chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграм chat-id",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_nick",
            field=models.CharField(
                blank=True,
                help_text="Укажите telegram-ник",
                max_length=50,
                null=True,
                verbose_name="Tg name",
            ),
        ),
    ]
